<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Modified from the original ASP bundle.</string>
	<key>fileTypes</key>
	<array>
		<string>bmx</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~B</string>
	<key>name</key>
	<string>BlitzMax</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.ending-space</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#round-brackets</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=\t)</string>
			<key>end</key>
			<string>(?=[^\t])</string>
			<key>name</key>
			<string>meta.leading-space</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.odd-tab.tabs</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.even-tab.tabs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\t)(\t)?</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?= )</string>
			<key>end</key>
			<string>(?=[^ ])</string>
			<key>name</key>
			<string>meta.leading-space</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.odd-tab.spaces</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.even-tab.spaces</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(  )(  )?</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.blitzmax</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.blitzmax</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.blitzmax</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.blitzmax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((?i:function))\s*([a-zA-Z_]\w*)\s*(\()([^)]*)(\)).*\n?</string>
			<key>name</key>
			<string>meta.function.blitzmax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>name</key>
			<string>comment.line.blitzmax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:rem)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i:end\s+rem)</string>
			<key>name</key>
			<string>comment.block.blitzmax</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.blitzmax</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.source.blitzmax</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.blitzmax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:(Global|Local|Field|Const)\s*\b([a-zA-Z_]\w*\b)\s*(?:\:([a-zA-Z_]\w*))\s*)</string>
			<key>name</key>
			<string>variable.other.dim.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\s*\b(Function|Type|End Function|End Type)\b\s*)</string>
			<key>name</key>
			<string>storage.type.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(SuperStrict|Strict|If|Then|Else|ElseIf|Else If|End If|While|Wend|For|To|Case|Select|End Select|Return|Continue|Until|Loop|Next|End|Exit)\b)</string>
			<key>name</key>
			<string>keyword.control.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(New|Self|Super|Min|Max|Not|Abs|Sgn|SizeOf|Varptr|And|Or|)\b)</string>
			<key>name</key>
			<string>keyword.operator.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\=|:(-|\+|\*|/))</string>
			<key>name</key>
			<string>keyword.operator.assignment.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|/|Mod|Shl|Shr|Sar)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Global|Local|Const)\b)</string>
			<key>name</key>
			<string>storage.modifier.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Global|Local|Const)\b)</string>
			<key>name</key>
			<string>storage.type.source.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\s*\b(Null|Pi|True|False)\b)</string>
			<key>name</key>
			<string>constant.language.blitzmax</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.blitzmax</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>""</string>
					<key>name</key>
					<string>constant.character.escape.apostrophe.blitzmax</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>-?\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.blitzmax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(TLink|TMap)\b)</string>
			<key>name</key>
			<string>support.type.blitzmax</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method.blitzmax</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:(\b[a-zA-Z_][a-zA-Z0-9_]*?\b)(?=\(\)?))</string>
			<key>name</key>
			<string>meta.function-call.blitzmax</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtinTypes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>variable.other.blitzmax</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>round-brackets</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.round-brackets.begin.blitzmax</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.round-brackets.end.blitzmax</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.round-brackets</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.blitzmax</string>
				</dict>
			</array>
		</dict>
		<key>builtinTypes</key>
		<dict>
			<key>match</key>
			<string>\b(?i:Byte|Short|Int|Long|Float|Double|String)\b</string>
			<key>name</key>
			<string>storage.type.source.blitzmax</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.blitzmax</string>
	<key>uuid</key>
	<string>d24349c9-661b-4e65-b13b-843d105b4d85</string>
</dict>
</plist>
